[package]
description = "Procedural macros for visit-rs"
edition = "2024"
license = "MIT"
name = "visit-rs-derive"
version = "0.1.4"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["extra-traits", "full"] }
